### PR TITLE
Fix customer related scheduler task failure and accounts not created

### PR DESCRIPTION
**Pull request by faerietree**
see #98

### CODE REVIEW

**Comment by faerietree** [comment]
From your comment on ai-typo3 the fix seems to be to update the Aimeos upgrade documentation by noting to re-enable the extension to reload `ext_tables.sql`?

Because fact is that the upgrade failed on TYPO3 7.x when following update documentation. It works with this proposed addition (that surely is not perfect, e.g. existence of `siteid` column might need checking?)

Isn't the `upgrade script` rather the place to add new columns than `ext_tables.sql`. The latter is initial setup and may once upon a time have been loaded from a much older Aimeos version?
Sorry if I got it wrong. Just trying to be helpful, i.e. prevent this fe_users.siteid missing issue for the future.

It seems we often are the first TYPO3 Aimeos to update and occasionally encounter small stones on our way. We could just patch and ignore it. But we think it's more helpful to provide a fix upstream.

**Comment by faerietree** [comment]
OK. I see. According to what you say, the problem is we did not use the Extension manager to upload the new extension?

So why some columns are added in `update scripts` and some via `ext_tables.sql`?

**Comment by aimeos** [comment]
`fe_users` is a TYPO3 tables and therefore it's managed the TYPO3 way using `ext_tables.sql`.

I see your point and it's always a good thing to prevent users from getting into such situations. Therefore, we should create the `siteid` column too when running the update script. This is specific for TYPO3 (schemas in all other integrations are managed via DBAL) so it must be in the `ai-typo3` extension. Are you able to provide a patch that implements a setup task in that extension?

**Comment by faerietree** [comment]
oki. will try

**Pull request closed without merging**
