### PR TITLE
Supplier SearchItems bugfix

### PR DESCRIPTION
**Pull request by Yvler**
Update the searchItems function of Supplier with the _buildItems function

### CODE REVIEW

**Comment by aimeos** [comment]
Would you mind to add the missing commit of the supplier item you've spoken from?

**Comment by Yvler** [comment]
do I still need to do the commit or did everything succeed?

**Comment by aimeos** [comment]
The manager is OK now but the supplier item changes are missing so the list items will be available. You said you've to change the supplier item constructor and this piece is missing.

**Comment by Yvler** [comment]
Did some commits to the files :) I guess that should be it

**Pull request merged**
