### PR TITLE
.gitignore ignored tracked file

### PR DESCRIPTION
**Pull request by jonaseberledmind**
controller/common/tests/config/resource.php

I am not sure what is desired here: remove and ignore OR keep and unignore (that's what I did)

### CODE REVIEW

**Comment by aimeos** [comment]
The `controller/common/tests/config/resource.php` file contains some required configurations for the tests only. For production environments it's not necessary but you will always get it when you make a `git clone` or `composer update`.

**Comment by jonaseberledmind** [comment]
Ok. I understand the reasoning behind it. I just got the PhpStorm .ignore plugin to moan about it and I would think it is cleaner to either track or ignore+untrack. 

For local changes that shall not be committed but still have a repository file version this also works:
http://archive.robwilkerson.org/2010/03/02/git-tip-ignore-changes-to-tracked-files/

**Comment by aimeos** [comment]
In that case the best solution is to change the line in the .gitignore file to match only the `/config/resource.php` file and not the file in `controller/common/tests/config/`.

Can you change this in that way?

**Comment by aimeos** [comment]
Does it work as you expect now because `config/resource.php` is also part of `controller/common/tests/config/resource.php`?

**Comment by jonaseberledmind** [comment]
Oh wow, you are right. Changing it.

**Pull request merged**
